### ISSUE TITLE
Conda-forge missing latest release

### ISSUE THREAD

**Issue by jamred** [capellaspace/console-client#28]
Hey there, the [conda-forge version](https://anaconda.org/conda-forge/capella-console-client) is still at 0.8.4 while the [pypi version](https://pypi.org/project/capella-console-client/) is at 0.9.0. Similarly, the github is the latest missing some recent release tags. 

Thanks!

**Comment by Shaunakde** [comment]
Thank you for bringing this up! I'll take a look and take a shot at remedying this and keep this issue up-to-date with the progress.

**Comment by grmpflh27** [comment]
@jamred, thanks for reporting 

Please find 0.9.0 on [conda-forge](https://anaconda.org/conda-forge/capella-console-client) + the respective release tag.

Thanks to @jordan-heemskerk for resolving this [here](https://github.com/conda-forge/capella-console-client-feedstock/pull/6)!
