### ISSUE TITLE
Python 3.12 support

### ISSUE THREAD

**Issue by scottyhq** [capellaspace/console-client#63]
Thanks for this client, it's very useful. I was trying to use the new tasking ability but noticed I didn't have 0.12 installed b/c I typically install from conda-forge when possible. But only 0.11 is available currently https://github.com/conda-forge/capella-console-client-feedstock/issues/16 

So I tried `pip install --upgrade capella-console-client` but alas "0.12.0 Requires-Python >=3.8,<3.12" . Just curious if 3.12 isn't supported for a particular reason or this can be bumped?
https://github.com/capellaspace/console-client/blob/acc1a3cc737cfae293a7be18bfcdab9e64aa8fd5/pyproject.toml#L30

**Comment by Shaunakde** [comment]
Thanks for posting this! I'm trying it out in an isolated docker to make sure. I don't think I should run into any issues, and we might be able to just set this to `<=3.12` - I'll report back soon and if all goes okay, submit a PR! 

SDe

**Comment by grmpflh27** [comment]
https://github.com/capellaspace/console-client/pull/64 addresses this, will be released as part of 0.13.0
